<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260602170935 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE cuenta_corriente_movimientos DROP FOREIGN KEY `fk_cc_cliente`');
        $this->addSql('ALTER TABLE cuenta_corriente_movimientos DROP FOREIGN KEY `fk_cc_usuario`');
        $this->addSql('ALTER TABLE movimientos_caja DROP FOREIGN KEY `fk_movimiento_turno`');
        $this->addSql('ALTER TABLE movimientos_caja DROP FOREIGN KEY `fk_movimiento_usuario`');
        $this->addSql('ALTER TABLE movimientos_caja DROP FOREIGN KEY `fk_movimiento_venta`');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY `fk_presupuesto_cliente`');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY `fk_presupuesto_usuario`');
        $this->addSql('ALTER TABLE presupuesto_detalles DROP FOREIGN KEY `fk_presupuesto_detalle_presupuesto`');
        $this->addSql('ALTER TABLE presupuesto_detalles DROP FOREIGN KEY `fk_presupuesto_detalle_producto`');
        $this->addSql('ALTER TABLE turnos_caja DROP FOREIGN KEY `fk_turno_cerrado_por`');
        $this->addSql('ALTER TABLE turnos_caja DROP FOREIGN KEY `fk_turno_usuario`');
        $this->addSql('ALTER TABLE usuarios DROP FOREIGN KEY `fk_usuario_role`');
        $this->addSql('ALTER TABLE ventas DROP FOREIGN KEY `fk_venta_cliente`');
        $this->addSql('ALTER TABLE ventas DROP FOREIGN KEY `fk_venta_usuario`');
        $this->addSql('ALTER TABLE ventas_pendientes DROP FOREIGN KEY `fk_pendiente_cliente`');
        $this->addSql('ALTER TABLE ventas_pendientes DROP FOREIGN KEY `fk_pendiente_usuario`');
        $this->addSql('ALTER TABLE venta_detalles DROP FOREIGN KEY `fk_detalle_producto`');
        $this->addSql('ALTER TABLE venta_detalles DROP FOREIGN KEY `fk_detalle_venta`');
        $this->addSql('DROP TABLE cache');
        $this->addSql('DROP TABLE cache_locks');
        $this->addSql('DROP TABLE clientes');
        $this->addSql('DROP TABLE cuenta_corriente_movimientos');
        $this->addSql('DROP TABLE failed_jobs');
        $this->addSql('DROP TABLE jobs');
        $this->addSql('DROP TABLE job_batches');
        $this->addSql('DROP TABLE login_attempts');
        $this->addSql('DROP TABLE marcas');
        $this->addSql('DROP TABLE migrations');
        $this->addSql('DROP TABLE movimientos_caja');
        $this->addSql('DROP TABLE password_reset_tokens');
        $this->addSql('DROP TABLE pedidos');
        $this->addSql('DROP TABLE presupuestos');
        $this->addSql('DROP TABLE presupuesto_detalles');
        $this->addSql('DROP TABLE proveedores');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE sessions');
        $this->addSql('DROP TABLE turnos_caja');
        $this->addSql('DROP TABLE unidades_medida');
        $this->addSql('DROP TABLE usuarios');
        $this->addSql('DROP TABLE ventas');
        $this->addSql('DROP TABLE ventas_pendientes');
        $this->addSql('DROP TABLE venta_detalles');
        $this->addSql('DROP INDEX idx_nombre ON categorias');
        $this->addSql('ALTER TABLE categorias DROP icono, CHANGE nombre nombre VARCHAR(255) NOT NULL, CHANGE descripcion descripcion LONGTEXT DEFAULT NULL, CHANGE activo activo TINYINT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE productos DROP FOREIGN KEY `fk_producto_categoria`');
        $this->addSql('ALTER TABLE productos DROP FOREIGN KEY `fk_producto_marca`');
        $this->addSql('ALTER TABLE productos DROP FOREIGN KEY `fk_producto_proveedor`');
        $this->addSql('ALTER TABLE productos DROP FOREIGN KEY `fk_producto_unidad`');
        $this->addSql('DROP INDEX idx_proveedor ON productos');
        $this->addSql('DROP INDEX idx_codigo_barra ON productos');
        $this->addSql('DROP INDEX idx_stock ON productos');
        $this->addSql('DROP INDEX idx_deleted ON productos');
        $this->addSql('DROP INDEX idx_marca ON productos');
        $this->addSql('DROP INDEX idx_nombre ON productos');
        $this->addSql('DROP INDEX fk_producto_unidad ON productos');
        $this->addSql('ALTER TABLE productos DROP codigo_barra, DROP modelo, DROP marca_id, DROP unidad_medida_id, DROP proveedor_id, DROP margen_ganancia, DROP unidad_medida, DROP stock_minimo, DROP ubicacion_deposito, DROP deleted_at, DROP created_at, DROP updated_at, CHANGE nombre nombre VARCHAR(255) DEFAULT NULL, CHANGE descripcion descripcion LONGTEXT DEFAULT NULL, CHANGE precio precio NUMERIC(10, 0) NOT NULL, CHANGE precio_costo precio_costo NUMERIC(10, 0) DEFAULT NULL, CHANGE stock stock NUMERIC(10, 3) NOT NULL, CHANGE imagen imagen VARCHAR(255) DEFAULT NULL, CHANGE activo activo TINYINT DEFAULT NULL');
        $this->addSql('ALTER TABLE productos ADD CONSTRAINT FK_767490E63397707A FOREIGN KEY (categoria_id) REFERENCES categorias (id)');
        $this->addSql('ALTER TABLE productos RENAME INDEX idx_categoria TO IDX_767490E63397707A');
        $this->addSql('ALTER TABLE users CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE email_verified_at email_verified_at DATETIME DEFAULT NULL, CHANGE remember_token remember_token VARCHAR(100) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE users RENAME INDEX users_email_unique TO UNIQ_1483A5E9E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cache (`key` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, value MEDIUMTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, expiration INT NOT NULL, INDEX cache_expiration_index (expiration), PRIMARY KEY (`key`)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE cache_locks (`key` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, owner VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, expiration INT NOT NULL, INDEX cache_locks_expiration_index (expiration), PRIMARY KEY (`key`)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE clientes (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, documento VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, tipo_documento ENUM(\'DNI\', \'CUIT\', \'CUIL\', \'Pasaporte\') CHARACTER SET utf8mb4 DEFAULT \'\'\'DNI\'\'\' COLLATE `utf8mb4_unicode_ci`, telefono VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, direccion TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ciudad VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, provincia VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, codigo_postal VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, saldo_cuenta_corriente NUMERIC(10, 2) DEFAULT \'0.00\', limite_credito NUMERIC(10, 2) DEFAULT \'0.00\', notas TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, activo TINYINT DEFAULT 1, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_nombre (nombre), INDEX idx_documento (documento), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE cuenta_corriente_movimientos (id INT AUTO_INCREMENT NOT NULL, cliente_id INT NOT NULL, tipo ENUM(\'venta\', \'pago\', \'ajuste_debito\', \'ajuste_credito\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, monto NUMERIC(10, 2) NOT NULL, saldo_historico NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, referencia_id INT DEFAULT NULL, descripcion TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, usuario_id INT NOT NULL, fecha DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_cliente (cliente_id), INDEX idx_fecha (fecha), INDEX fk_cc_usuario (usuario_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE failed_jobs (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, uuid VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, connection TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, queue TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, payload LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, exception LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, failed_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, UNIQUE INDEX failed_jobs_uuid_unique (uuid), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE jobs (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, queue VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, payload LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, attempts TINYINT NOT NULL, reserved_at INT UNSIGNED DEFAULT NULL, available_at INT UNSIGNED NOT NULL, created_at INT UNSIGNED NOT NULL, INDEX jobs_queue_index (queue), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE job_batches (id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, total_jobs INT NOT NULL, pending_jobs INT NOT NULL, failed_jobs INT NOT NULL, failed_job_ids LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, options MEDIUMTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cancelled_at INT DEFAULT NULL, created_at INT NOT NULL, finished_at INT DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE login_attempts (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ip_address VARCHAR(45) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_agent TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, success TINYINT DEFAULT 0, attempted_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_attempted_at (attempted_at), INDEX idx_username (username), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE marcas (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, pais_origen VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, descripcion TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, activo TINYINT DEFAULT 1, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_nombre (nombre), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE migrations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, migration VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, batch INT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE movimientos_caja (id INT AUTO_INCREMENT NOT NULL, turno_id INT NOT NULL, tipo ENUM(\'venta\', \'ingreso\', \'egreso\', \'apertura\', \'cierre\', \'inicial\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, monto NUMERIC(10, 2) NOT NULL, descripcion TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, venta_id INT DEFAULT NULL, usuario_id INT NOT NULL, fecha DATETIME DEFAULT \'current_timestamp()\' NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX fk_movimiento_usuario (usuario_id), INDEX idx_tipo (tipo), INDEX idx_venta (venta_id), INDEX idx_fecha (fecha), INDEX idx_turno (turno_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE password_reset_tokens (email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, token VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT \'NULL\', PRIMARY KEY (email)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pedidos (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, descripcion TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, codigo VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, cantidad INT DEFAULT 1 NOT NULL, categoria_id INT DEFAULT NULL, proveedor VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, estado ENUM(\'pendiente\', \'comprado\', \'cancelado\') CHARACTER SET utf8mb4 DEFAULT \'\'\'pendiente\'\'\' COLLATE `utf8mb4_general_ci`, visible TINYINT DEFAULT 1, observaciones TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'NULL\', PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE presupuestos (id INT AUTO_INCREMENT NOT NULL, usuario_id INT NOT NULL, cliente_id INT DEFAULT NULL, total NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, subtotal NUMERIC(10, 2) DEFAULT \'0.00\', descuento_porcentaje NUMERIC(5, 2) DEFAULT \'0.00\', descuento_monto NUMERIC(10, 2) DEFAULT \'0.00\', estado ENUM(\'borrador\', \'enviado\', \'aprobado\', \'rechazado\', \'convertido\') CHARACTER SET utf8mb4 DEFAULT \'\'\'borrador\'\'\' COLLATE `utf8mb4_unicode_ci`, notas TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, fecha DATETIME DEFAULT \'current_timestamp()\' NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_fecha (fecha), INDEX idx_usuario (usuario_id), INDEX idx_cliente (cliente_id), INDEX idx_estado (estado), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE presupuesto_detalles (id INT AUTO_INCREMENT NOT NULL, presupuesto_id INT NOT NULL, producto_id INT NOT NULL, cantidad NUMERIC(10, 3) NOT NULL, precio NUMERIC(10, 2) NOT NULL, descuento_porcentaje NUMERIC(5, 2) DEFAULT \'0.00\', descuento_monto NUMERIC(10, 2) DEFAULT \'0.00\', subtotal NUMERIC(10, 2) NOT NULL, INDEX idx_producto (producto_id), INDEX idx_presupuesto (presupuesto_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE proveedores (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, razon_social VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, cuit VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, telefono VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, direccion TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ciudad VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, provincia VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, codigo_postal VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, contacto VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, notas TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, activo TINYINT DEFAULT 1, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_nombre (nombre), INDEX idx_cuit (cuit), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE roles (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, descripcion TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, permisos TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'JSON con permisos del rol\', activo TINYINT DEFAULT 1, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, UNIQUE INDEX nombre (nombre), INDEX idx_nombre (nombre), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE sessions (id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_id BIGINT UNSIGNED DEFAULT NULL, ip_address VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, user_agent TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, payload LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, last_activity INT NOT NULL, INDEX sessions_user_id_index (user_id), INDEX sessions_last_activity_index (last_activity), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE turnos_caja (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, usuario_id INT DEFAULT NULL, usuario_nombre VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, monto_inicial NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, monto_final NUMERIC(10, 2) DEFAULT \'NULL\', monto_esperado NUMERIC(10, 2) DEFAULT \'NULL\', diferencia NUMERIC(10, 2) DEFAULT \'NULL\', estado ENUM(\'abierto\', \'cerrado\') CHARACTER SET utf8mb4 DEFAULT \'\'\'abierto\'\'\' COLLATE `utf8mb4_unicode_ci`, fecha_apertura DATETIME DEFAULT \'current_timestamp()\' NOT NULL, fecha_cierre DATETIME DEFAULT \'NULL\', notas_apertura TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, notas_cierre TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cerrado_por INT DEFAULT NULL, INDEX idx_fecha_apertura (fecha_apertura), INDEX fk_turno_cerrado_por (cerrado_por), INDEX idx_user (user_id), INDEX idx_estado (estado), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE unidades_medida (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, abreviatura VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, tipo ENUM(\'unidad\', \'longitud\', \'peso\', \'volumen\', \'area\', \'otro\') CHARACTER SET utf8mb4 DEFAULT \'\'\'unidad\'\'\' COLLATE `utf8mb4_unicode_ci`, activo TINYINT DEFAULT 1, INDEX idx_nombre (nombre), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE usuarios (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, password VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nombre VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, rol ENUM(\'admin\', \'vendedor\', \'cajero\') CHARACTER SET utf8mb4 DEFAULT \'\'\'vendedor\'\'\' NOT NULL COLLATE `utf8mb4_unicode_ci`, role_id INT DEFAULT NULL, activo TINYINT DEFAULT 1, is_active TINYINT DEFAULT 1, last_login DATETIME DEFAULT \'NULL\', failed_attempts INT DEFAULT 0, last_failed_login DATETIME DEFAULT \'NULL\', created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX fk_usuario_role (role_id), UNIQUE INDEX username (username), INDEX idx_username (username), INDEX idx_rol (rol), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ventas (id INT AUTO_INCREMENT NOT NULL, usuario_id INT NOT NULL, cliente_id INT DEFAULT NULL, total NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, subtotal NUMERIC(10, 2) DEFAULT \'0.00\', descuento_porcentaje NUMERIC(5, 2) DEFAULT \'0.00\', descuento_monto NUMERIC(10, 2) DEFAULT \'0.00\', monto_pagado NUMERIC(10, 2) DEFAULT \'0.00\', cambio NUMERIC(10, 2) DEFAULT \'0.00\', metodo_pago ENUM(\'efectivo\', \'tarjeta_debito\', \'tarjeta_credito\', \'transferencia\', \'cuenta_corriente\', \'otro\') CHARACTER SET utf8mb4 DEFAULT \'\'\'efectivo\'\'\' COLLATE `utf8mb4_unicode_ci`, metodo_pago_secundario VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, monto_pago_secundario NUMERIC(10, 2) DEFAULT \'0.00\', estado ENUM(\'completada\', \'pendiente\', \'cancelada\') CHARACTER SET utf8mb4 DEFAULT \'\'\'completada\'\'\' COLLATE `utf8mb4_unicode_ci`, notas TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, fecha DATETIME DEFAULT \'current_timestamp()\' NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_metodo_pago (metodo_pago), INDEX idx_cliente (cliente_id), INDEX idx_fecha (fecha), INDEX idx_estado (estado), INDEX idx_usuario (usuario_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ventas_pendientes (id INT AUTO_INCREMENT NOT NULL, usuario_id INT NOT NULL, cliente_id INT DEFAULT NULL, items LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, subtotal NUMERIC(10, 2) DEFAULT \'0.00\', descuento NUMERIC(10, 2) DEFAULT \'0.00\', total NUMERIC(10, 2) DEFAULT \'0.00\', notas TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_usuario (usuario_id), INDEX idx_cliente (cliente_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE venta_detalles (id INT AUTO_INCREMENT NOT NULL, venta_id INT NOT NULL, producto_id INT NOT NULL, cantidad NUMERIC(10, 3) NOT NULL, precio NUMERIC(10, 2) NOT NULL, precio_costo NUMERIC(10, 2) DEFAULT \'0.00\', descuento_porcentaje NUMERIC(5, 2) DEFAULT \'0.00\', descuento_monto NUMERIC(10, 2) DEFAULT \'0.00\', subtotal NUMERIC(10, 2) NOT NULL, subtotal_sin_descuento NUMERIC(10, 2) DEFAULT \'0.00\', INDEX idx_venta (venta_id), INDEX idx_producto (producto_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE cuenta_corriente_movimientos ADD CONSTRAINT `fk_cc_cliente` FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cuenta_corriente_movimientos ADD CONSTRAINT `fk_cc_usuario` FOREIGN KEY (usuario_id) REFERENCES usuarios (id)');
        $this->addSql('ALTER TABLE movimientos_caja ADD CONSTRAINT `fk_movimiento_turno` FOREIGN KEY (turno_id) REFERENCES turnos_caja (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE movimientos_caja ADD CONSTRAINT `fk_movimiento_usuario` FOREIGN KEY (usuario_id) REFERENCES usuarios (id)');
        $this->addSql('ALTER TABLE movimientos_caja ADD CONSTRAINT `fk_movimiento_venta` FOREIGN KEY (venta_id) REFERENCES ventas (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT `fk_presupuesto_cliente` FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT `fk_presupuesto_usuario` FOREIGN KEY (usuario_id) REFERENCES usuarios (id)');
        $this->addSql('ALTER TABLE presupuesto_detalles ADD CONSTRAINT `fk_presupuesto_detalle_presupuesto` FOREIGN KEY (presupuesto_id) REFERENCES presupuestos (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE presupuesto_detalles ADD CONSTRAINT `fk_presupuesto_detalle_producto` FOREIGN KEY (producto_id) REFERENCES productos (id)');
        $this->addSql('ALTER TABLE turnos_caja ADD CONSTRAINT `fk_turno_cerrado_por` FOREIGN KEY (cerrado_por) REFERENCES usuarios (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE turnos_caja ADD CONSTRAINT `fk_turno_usuario` FOREIGN KEY (user_id) REFERENCES usuarios (id)');
        $this->addSql('ALTER TABLE usuarios ADD CONSTRAINT `fk_usuario_role` FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ventas ADD CONSTRAINT `fk_venta_cliente` FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ventas ADD CONSTRAINT `fk_venta_usuario` FOREIGN KEY (usuario_id) REFERENCES usuarios (id)');
        $this->addSql('ALTER TABLE ventas_pendientes ADD CONSTRAINT `fk_pendiente_cliente` FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ventas_pendientes ADD CONSTRAINT `fk_pendiente_usuario` FOREIGN KEY (usuario_id) REFERENCES usuarios (id)');
        $this->addSql('ALTER TABLE venta_detalles ADD CONSTRAINT `fk_detalle_producto` FOREIGN KEY (producto_id) REFERENCES productos (id)');
        $this->addSql('ALTER TABLE venta_detalles ADD CONSTRAINT `fk_detalle_venta` FOREIGN KEY (venta_id) REFERENCES ventas (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE categorias ADD icono VARCHAR(50) DEFAULT \'\'\'fa-box\'\'\', CHANGE nombre nombre VARCHAR(100) NOT NULL, CHANGE descripcion descripcion TEXT DEFAULT NULL, CHANGE activo activo TINYINT DEFAULT 1, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL');
        $this->addSql('CREATE INDEX idx_nombre ON categorias (nombre)');
        $this->addSql('ALTER TABLE productos DROP FOREIGN KEY FK_767490E63397707A');
        $this->addSql('ALTER TABLE productos ADD codigo_barra VARCHAR(50) DEFAULT \'NULL\', ADD modelo VARCHAR(100) DEFAULT \'NULL\', ADD marca_id INT DEFAULT NULL, ADD unidad_medida_id INT DEFAULT 1, ADD proveedor_id INT DEFAULT NULL, ADD margen_ganancia NUMERIC(5, 2) DEFAULT \'30.00\', ADD unidad_medida VARCHAR(20) DEFAULT \'\'\'unid\'\'\', ADD stock_minimo NUMERIC(10, 3) DEFAULT \'0.000\' NOT NULL, ADD ubicacion_deposito VARCHAR(50) DEFAULT \'NULL\', ADD deleted_at DATETIME DEFAULT \'NULL\', ADD created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, ADD updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE nombre nombre VARCHAR(200) NOT NULL, CHANGE descripcion descripcion TEXT DEFAULT NULL, CHANGE precio precio NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, CHANGE precio_costo precio_costo NUMERIC(10, 2) DEFAULT \'0.00\', CHANGE stock stock NUMERIC(10, 3) DEFAULT \'0.000\' NOT NULL, CHANGE imagen imagen VARCHAR(255) DEFAULT \'NULL\', CHANGE activo activo TINYINT DEFAULT 1');
        $this->addSql('ALTER TABLE productos ADD CONSTRAINT `fk_producto_categoria` FOREIGN KEY (categoria_id) REFERENCES categorias (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE productos ADD CONSTRAINT `fk_producto_marca` FOREIGN KEY (marca_id) REFERENCES marcas (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE productos ADD CONSTRAINT `fk_producto_proveedor` FOREIGN KEY (proveedor_id) REFERENCES proveedores (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE productos ADD CONSTRAINT `fk_producto_unidad` FOREIGN KEY (unidad_medida_id) REFERENCES unidades_medida (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX idx_proveedor ON productos (proveedor_id)');
        $this->addSql('CREATE INDEX idx_codigo_barra ON productos (codigo_barra)');
        $this->addSql('CREATE INDEX idx_stock ON productos (stock)');
        $this->addSql('CREATE INDEX idx_deleted ON productos (deleted_at)');
        $this->addSql('CREATE INDEX idx_marca ON productos (marca_id)');
        $this->addSql('CREATE INDEX idx_nombre ON productos (nombre)');
        $this->addSql('CREATE INDEX fk_producto_unidad ON productos (unidad_medida_id)');
        $this->addSql('ALTER TABLE productos RENAME INDEX idx_767490e63397707a TO idx_categoria');
        $this->addSql('ALTER TABLE users CHANGE name name VARCHAR(255) NOT NULL, CHANGE email_verified_at email_verified_at DATETIME DEFAULT \'NULL\', CHANGE remember_token remember_token VARCHAR(100) DEFAULT \'NULL\', CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE users RENAME INDEX uniq_1483a5e9e7927c74 TO users_email_unique');
    }
}
